language: csharp
solution: EscritorDeNumeroPorExtenso.sln
install:
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release EscritaPorExtenso.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe EscritaPorExtenso.Testes/bin/Release/EscritaPorExtenso.Testes.dll
